{% set name = "mongogrant" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mongogrant-{{ version }}.tar.gz
  sha256: ad494b8638adfa840cdd5568af44448dd43771b58102550cf7c61402b1620ab4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mgrant = mongogrant.scripts.mgrant:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - flask >=1.0
    - pymongo >=3.8
    - python >=3.6
    - requests

test:
  imports:
    - mongogrant
    - mongogrant.scripts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/mongogrant/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: grant username and password credentials for roles on mongo databases via email verification
  description: |
    So, your friendly neighborhood mongogranter says you know have access
    to a database through your email address. 
  doc_url: https://github.com/materialsproject/mongogrant/
  dev_url: https://github.com/materialsproject/mongogrant/

extra:
  recipe-maintainers:
    - jan-janssen
